### PR TITLE
Modified tests for robolectric

### PR DESCRIPTION
**Pull request by Matathiasq13824**
Last week, we had a problem with the stability of some tests in CI, leading to the removal of two tests.
Using Robolectric, I have tried to fix them, which has moved `MainActivityTest` in the unit test folder.
I think that there is still room for improvement for the coverage but I was the best I could do with the time allocated.

### CODE REVIEW

**Review by ValentinAebi — COMMENTED** [review]
`grantPremission` and `denyPermission look like they have the same code. Why is it? That is very weird since they have different roles.

**Review by felko — APPROVED** [review]
Thank you for fixing this, I have nothing to add other than what @ValentinAebi said.

**Comment by Matathiasq13824** [comment]
> `grantPremission` and `denyPermission` look like they have the same code. Why is it? That is very weird since they have different roles.

The code before was also very similar. The most important part are the 'shadowApplication.grantPermissions' and `shadowApplication.denyPermissions` who will give or not the permission to access the camera

**Review by Voxanimus — APPROVED** [review]
It will be so usefull thanks

**Comment by ValentinAebi** [comment]
> The code before was also very similar. The most important part are the `shadowApplication.grantPermissions` and `shadowApplication.denyPermissions` who will give or not the permission to access the camera

Yes but you never call `shadowApplication.denyPermissions`. You use `shadowApplication.grantPermissions` in both `grantPermission` and `denyPermission`

**Pull request merged**
